name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container: [1,2]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: 56b73a2d-e94e-4c61-bd36-2c5e800d5fab

      - name: Upload relatório
        uses: actions/upload-artifact@v3
        with:
          name: Relatório
          path: cypress/reports/html